"""add kindle_status to conversions

Revision ID: ad371f574006
Revises: eff974f5afda
Create Date: 2026-03-17 13:59:13.195116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad371f574006'
down_revision: Union[str, Sequence[str], None] = 'eff974f5afda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversions', sa.Column('kindle_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversions', 'kindle_status')
    # ### end Alembic commands ###
